[package]
name = "shard"
version = "0.1.0"
edition = "2021"
description = "A compiler for the Shard programming language."
license = "MIT"
repository = "https://github.com/anthonysSlab/shard"


[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
clap_complete = "4.4.3"
libc = "0.2.149"
log = "0.4.20"
# strp = "1.1.2"

[build-dependencies]
cc = "1.0.83"
